import numpy as np

x = np.load("X_fbank.npy")
y = np.load("y_fbank.npy")

print("X shape of X_fbank.py:", x.shape)
print("X dtype:", x.dtype)

print("y shape:", y.shape)
print("y dtype:", y.dtype)

print("eembc resnet")
x1=np.load("sample_trained_models/keras/eembc_resnet/X.npy")
y1=np.load("sample_trained_models/keras/eembc_resnet/Y.npy")
print("X shape :",x1.shape)
print("y shape :",y1.shape)
print("X dtype:",x1.dtype)
print("Y dtype:",y1.dtype)
print()
print("lstm")
x2=np.load("sample_trained_models/keras/lstm/X.npy")
y2=np.load("sample_trained_models/keras/lstm/Y.npy")
print("X shape :",x2.shape)
print("y shape :",y2.shape)
print("X dtype:",x2.dtype)
print("Y dtype:",y2.dtype)
print()
print("mobilenet_v1_alpha025")
x3=np.load("sample_trained_models/keras/mobilenet_v1_alpha025/X.npy")
y3=np.load("sample_trained_models/keras/mobilenet_v1_alpha025/Y.npy")
print("X shape :",x3.shape)
print("y shape :",y3.shape)
print("X dtype:",x3.dtype)
print("Y dtype:",y3.dtype)
print()
print("model_qat_dense")
x4=np.load("sample_trained_models/keras/model_qat_dense/X.npy")
y4=np.load("sample_trained_models/keras/model_qat_dense/Y.npy")
print("X shape :",x4.shape)
print("y shape :",y4.shape)
print("X dtype:",x4.dtype)
print("Y dtype:",y4.dtype)
print()
print("model_with_16bit_input")
x5=np.load("sample_trained_models/keras/model_with_16bit_input/X.npy")
y5=np.load("sample_trained_models/keras/model_with_16bit_input/Y.npy")
print("X shape :",x5.shape)
print("y shape :",y5.shape)
print("X dtype:",x5.dtype)
print("Y dtype:",y5.dtype)
print()
print("multi_layer_perceptron")
x6=np.load("sample_trained_models/keras/multi_layer_perceptron/X.npy")
y6=np.load("sample_trained_models/keras/multi_layer_perceptron/Y.npy")
print("X shape :",x6.shape)
print("y shape :",y6.shape)
print("X dtype:",x6.dtype)
print("Y dtype:",y6.dtype)
print()